version: '3.3'
services:
  webserver:
    build:
      dockerfile: php.Dockerfile
      context: .
    restart: always
    volumes:
      - "./aplikasimarketing/:/var/www/html/"
    ports:
      - '8080:80'

  mysql-server:
    image: mysql:8.0.19
    restart: always
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: mkfs.vfat
      MYSQL_DATABASE: marketing
      MYSQL_ROOT_PASSWORD: mkfs.vfat
    volumes:
      - mysql-data:/var/lib/mysql
      - ./aplikasimarketing/db_mysql/marketing.sql:/docker-entrypoint-initdb.d/marketing.sql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: always
    environment:
      PMA_HOST: mysql-server
      PMA_USER: root
      PMA_PASSSWORD: mkfs.vfat
    ports:
      - "5000:80"
volumes:
  mysql-data:
